package regression;



import org.testng.annotations.Test;

import base.BaseTest;
import pages.BasePage.AccountType;
import pages.BasePage.Login;

public class Autorenewal extends BaseTest {	
	
	
@Test(description = "R66_JEU_MFD_JEPP_Auto_Renewal_Annual_Yes_VISA_Error_MasterCC_3DS1_NoFriction")
public void R66_JEU_MFD_JEPP_Auto_Renewal_Annual_Yes__VISA_Error_MasterCC_3DS1_NoFriction() {
	     home.
			 GoTo_LogIn()
			.Login_With_Credentials_And_Verify_Login(Login.jeuautoRenewal)
			.Empty_Out_Cart()	 
			.Add_This_Product_To_Cart(simpleProduct.get("MFDProduct"))
			.Add_This_Product_To_Cart(simpleProduct.get("pre-configJepp"))
		  	.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Annual()
			.Select_Device(aircraftDetailsTier1.get("devicemodelG1K"))
			.Add_AlaCarte_Product_To_Cart()
			.Checkout_From_Alacarte()
			.Checkout_With_Cart()
			.Add_New_Shipping_Address(basicAddress)
			.Use_Default_Shipping_Method()
			.Use_Credit_Card_Payment(ErrorVisaCardFriction)
			.Auto_Renewal_Selection(AutoRenewal, "Yes")
			.Use_Existing_Billing_Address_CC()
			.FrictionFlow_Validation_3DS2(ErrorVisaCardFriction, "submit")
		    .Validate_ErrorCard_On_Checkout(ErrorVisaCardFriction)		
			.Use_Credit_Card_Payment(masterCard3DS1NoFriction)// updated 3ds1 friction to 3ds1 fritionless 
			.Auto_Renewal_Selection(AutoRenewal,"Yes")
			.saveCardCheck()
			.Use_Existing_Billing_Address_CC()
			.Auto_Renewal_validation()
			.Auto_Renewal_Price_Check()
			.Place_Order()
			.Validate_Autorenewal_Annual_OrderConfirmation(ordertype.get("RenewalAnnualYes"))
			.Verify_Order()
			.Validate_Autorenewal_Annual_OrderDetails(ordertype.get("RenewalAnnualYes"))
			.LogOut_Account();

		}
 @Test(description= "R67_JUS_Mixed_Cart_Auto_renewal_Annual_Monthly_OneTime_Yes_Amex_3DS2_NoFriction")
 public void R67_JUS_Mixed_Cart_Auto_renewal_Annual_Monthly_OneTime_Yes_Amex_3DS2_NoFriction() {		
		home
			.GoTo_LogIn()
		    .Login_With_Credentials_And_Verify_Login(Login.autoRenewal)
	        .Empty_Out_Cart()   
			.Add_This_Product_To_Cart(simpleProduct.get("AviallFullfilled"))
			.Add_This_Product_To_Cart(simpleProduct.get("JeppFullfilled"))
			.Add_This_Product_To_Cart(simpleProduct.get("onlinelearningProduct"))
			.Add_This_Product_To_Cart(simpleProduct.get("hardgoodProduct2"))
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_OneTime()
			.Select_Device(aircraftDetailsTier1.get("devicemodelG1K"))
			.Verify_Category(alacarteCategories.get("CategoryNav"))
			.Verify_Category(alacarteCategories.get("CategoryEDS"))
			.Add_AlaCarte_Product_To_Cart()		
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Monthly()
			.Select_Device(aircraftDetailsTier1.get("devicemodelG3K"))
			.Add_AlaCarte_Product_To_Cart()
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Annual()
			.Choose_Fly_Location(alacarteRegions.get("regionPCF"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Annual()
			.Select_Device(aircraftDetailsTier1.get("devicemodelAVDEX5"))
			.Add_AlaCarte_Product_To_Cart()
			.Checkout_With_Cart()
			.Add_New_Shipping_Address(basicAddress)			
			.Use_Default_Shipping_Method()
			.Use_Credit_Card_Payment(amexCard3DS2NoFriction)
			.Auto_Renewal_Selection(AutoRenewal,"Yes")
			.Add_New_Billing_Address_CC(billingAddress)
			.Auto_Renewal_validation()			
			.Place_Order()
			.Validate_Autorenewal_Annual_OrderConfirmation(ordertype.get("Mixed"))			
			.Verify_Order()	
			.Validate_Autorenewal_Annual_OrderDetails(ordertype.get("Mixed"))
	        .LogOut_Account();		
		}
@Test(description = "R68_Subscription_No_Auto_Renewal_non_availability_Account_PO_EditCart_Amex_3DS2_No_FF")
 
 public void R68_Subscription_No_Auto_Renewal_non_availability_Account_PO_EditCart_Amex_3DS2_No_FF() {
			home.GoTo_LogIn()
			.Login_With_Credentials_And_Verify_Login(Login.norenewal22)
			.Empty_Out_Cart()
			.GoTo_HomePage()// below no subscription  check added
			.Goto_MySubscriptions()
			.Validate_PaymentInfo_Renewal_Subscriptions()
			.Verify_No_AutoPaymentInfo_On_Subscription()
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier3)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Annual()
			.Select_Device(aircraftDetailsTier3.get("devicemodelG1K"))
			.Add_AlaCarte_Product_To_Cart()
			.Checkout_With_Cart()
			.Add_New_Shipping_Address(basicAddress)
			.Use_Default_Shipping_Method()
			.Use_Account_Payment()
			.Auto_Renewal_noCheck()
			.Add_New_Billing_Address(billingAddress)
			.Edit_this_Cart()
			.Empty_Out_Cart()
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier3)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_OneTime()
			.Select_Device(aircraftDetailsTier3.get("devicemodelG1K"))
			.Add_AlaCarte_Product_To_Cart()
			.Checkout_From_Alacarte()
			.Checkout_With_Cart()
			.Use_Existing_Shipping_Address()
			.Use_Default_Shipping_Method()
			.Use_Credit_Card_Payment(amexCard3DS2NoFriction)
			.Auto_Renewal_noCheck()
			.Use_Existing_Billing_Address_CC()	
			.Place_Order()
			.Validate_Autorenewal_Annual_OrderConfirmation(ordertype.get("NoRenewal"))
			.Verify_Order()
			.Validate_Autorenewal_Annual_OrderDetails(ordertype.get("NoRenewal"))
			.LogOut_Account();

		}

@Test(description = "R69Jepp and MFD _annual_onetime(Same tier diff devices)_Monthly(diff tiers, same devices)Auto renewal_Y_MasterCC_3DS2_Yes_NF")
 public void R69_Annual_Auto_Renewal_Yes_Subscriptions_Check_diff_devices() {

			home
			.GoTo_LogIn()
			.Login_With_Credentials_And_Verify_Login(Login.jusrenewalbundle)
			.Empty_Out_Cart()
			.Goto_OrderHistory()
			.Capture_SubscriptionDetails_OnOrderDetailsPage(masterCard3DS2NoFriction)
		    .Goto_MySubscriptions()
			.Validate_PaymentInfo_Renewal_Subscriptions()
			.Verify_AutoPayment_On_Subscriptions()
			.Add_Credit_Card_Payment_Autopay(masterCard3DS2NoFriction,billingAddress)
			
			.Navigate_Buy_Database()// added from here
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_OneTime()
			.Select_Device(aircraftDetailsTier1.get("devicemodelG1K"))
			.Verify_Category(alacarteCategories.get("CategoryNav"))
			.Verify_Category(alacarteCategories.get("CategoryEDS"))
			.Add_AlaCarte_Product_To_Cart()// add annual checks to the above flow
			
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Annual()
			.Select_Device(aircraftDetailsTier1.get("devicemodelG3K"))
			.Verify_Category(alacarteCategories.get("CategoryNav"))
			.Verify_Category(alacarteCategories.get("CategoryEDS"))
			.Add_AlaCarte_Product_To_Cart()
			
			//Monthly
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier2)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Monthly()
			.Select_Device(aircraftDetailsTier2.get("devicemodelG1K"))
			.Add_AlaCarte_Product_To_Cart()
			.Validate_AlaCarte_Product_Info_InCart(aircraftDetailsTier2)
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier1)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Monthly()
			.Select_Device(aircraftDetailsTier1.get("devicemodelG1K"))
			.Add_AlaCarte_Product_To_Cart()
			.Validate_AlaCarte_Product_Info_InCart(aircraftDetailsTier1)
			.Navigate_Buy_Database()
			.Select_Your_Aircraft(aircraftDetailsTier3)
			.Choose_Fly_Location(alacarteRegions.get("regionNA"))
			.Select_Individual_Avionics()
			.Select_Length_Of_Coverage_Monthly()
			.Select_Device(aircraftDetailsTier3.get("devicemodelG1K"))
			.Add_AlaCarte_Product_To_Cart()
			.Validate_AlaCarte_Product_Info_InCart(aircraftDetailsTier3)
			.Checkout_With_Cart()
			.Add_New_Shipping_Address(basicAddress)
			.Use_Default_Shipping_Method()
			.Monthly_AutoRenewal_Validation(AutoRenewal)
			.Auto_Renewal_Selection(AutoRenewal, "NoSelection")
			.Auto_Renewal_Selection(AutoRenewal,"Yes")
			.saveCardCheck()
			.Use_Credit_Card_Payment(masterCard3DS2NoFriction)
			.Use_Existing_Billing_Address_CC()
			.Place_Order()
			.Validate_Autorenewal_Annual_OrderConfirmation(ordertype.get("Monthly&Annual"))
			.Verify_Order()
			.Validate_Autorenewal_Annual_OrderDetails(ordertype.get("Monthly&Annual"))
		   
			.LogOut_Account();

		}	
 @Test(description= "R70_Mixed cart_with tier2_same_device_category_check_ Auto renewal with Yes to auto renewal")
 public void R70_Mixed_cart_with_tier2_same_device_category_check_Auto_renewal_with_Yes() {		
			home
			   .GoTo_LogIn()
			   .Login_With_Credentials_And_Verify_Login(Login.jaurenewal)
			   .Empty_Out_Cart()
			   .Goto_OrderHistory()
			   .Capture_SubscriptionDetails_OnOrderDetailsPage(masterCard3DS2NoFriction)
			   .Goto_MySubscriptions()
			   .Validate_PaymentInfo_Renewal_Subscriptions()
			   .Verify_AutoPayment_On_Subscriptions()
			   .Add_Credit_Card_Payment_Autopay(masterCard3DS2NoFriction, AUbilling)
			   .Navigate_Buy_Database()
				.Select_Your_Aircraft(aircraftDetailsTier2) 
				.Choose_Fly_Location(alacarteRegions.get("regionNA"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_Monthly()
				.Select_Device(aircraftDetailsTier2.get("devicemodelG1K"))
				.Add_AlaCarte_Product_To_Cart()
				.Validate_AlaCarte_Product_Info_InCart(aircraftDetailsTier2)
				.Navigate_Buy_Database()
				.Select_Your_Aircraft(aircraftDetailsTier2)
				.Choose_Fly_Location(alacarteRegions.get("regionNA"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_Monthly()
				.Select_Device(aircraftDetailsTier2.get("devicemodelG3K"))
				.Add_AlaCarte_Product_To_Cart()
				.Validate_AlaCarte_Product_Info_InCart(aircraftDetailsTier2)
				.Navigate_Buy_Database()
				.Select_Your_Aircraft(aircraftDetailsTier2)
				.Choose_Fly_Location(alacarteRegions.get("regionNA"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_Monthly()
				.Select_Device(aircraftDetailsTier2.get("devicemodelG500TXi"))
				.Add_AlaCarte_Product_To_Cart()
				.Validate_AlaCarte_Product_Info_InCart(aircraftDetailsTier2)
				.Checkout_With_Cart()
			    .Navigate_Buy_Database()
				.Select_Your_Aircraft(aircraftDetailsTier2)
				.Choose_Fly_Location(alacarteRegions.get("regionNA"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_OneTime()
				.Select_Device(aircraftDetailsTier2.get("devicemodelG1K"))
				.Verify_Category(alacarteCategories.get("CategoryNav"))
				.Verify_Category(alacarteCategories.get("CategoryEDS"))
				
				.Add_AlaCarte_Product_To_Cart()		
				.Navigate_Buy_Database()
				.Select_Your_Aircraft(aircraftDetailsTier2)
				.Choose_Fly_Location(alacarteRegions.get("regionNA"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_Annual()
				.Choose_Fly_Location(alacarteRegions.get("regionPCF"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_Annual()
				.Select_Device(aircraftDetailsTier2.get("devicemodelAVDEX5"))
				.Verify_Category(alacarteCategories.get("CategoryNav"))
				//.Verify_Category(alacarteCategories.get("CategoryEDS"))
				.Validate_Coverage(alacarteLOS.get("LSAN"))
				.Add_AlaCarte_Product_To_Cart()
				.GoTo_AircraftDetails()
				.Navigate_To_BuyDB_Screen_From_AircraftDetails()
				.Select_Your_Aircraft(aircraftDetailsTier2)
				.Choose_Fly_Location(alacarteRegions.get("regionNA"))
				.Select_Individual_Avionics()
				.Select_Length_Of_Coverage_Annual()
				.Select_Device(aircraftDetailsTier2.get("devicemodelG500TXi"))
				.Verify_Category(alacarteCategories.get("CategoryObs"))
				.Verify_Category(alacarteCategories.get("CategoryTrn"))
				//.Verify_Category(alacarteCategories.get("CategoryObp"))
				.Verify_Category(alacarteCategories.get("CategorySft"))
				.Verify_Category(alacarteCategories.get("CategoryNav"))
				//.Validate_Coverage(alacarteLOS.get("LSAN"))
				.Add_AlaCarte_Product_To_Cart()
				.Checkout_With_Cart()
				.Add_New_Shipping_Address(newNZShippingAddress)			
				.Use_Default_Shipping_Method()
				.Use_Credit_Card_Payment(masterCard3DS2NoFriction)
				.Auto_Renewal_Selection(AutoRenewal,"Yes")
				.saveCardCheck()
				.Add_New_Billing_Address_CC(AUbilling)
				.Auto_Renewal_validation()			
				.Place_Order()
				.Validate_Autorenewal_Annual_OrderConfirmation(ordertype.get("Mixed"))			
				.Verify_Order()	
				.Validate_Autorenewal_Annual_OrderDetails(ordertype.get("Mixed"))
				.LogOut_Account();		


						}
	  
 @Test(description = "R71_Auto Renewal_Subscription Listing Page_Visa_3DS2_FF")
 public void R71_Validate_AutoRenewalCC_OnSubscriptionListing() {
    				home
					.GoTo_LogIn()
					.Login_With_Credentials_And_Verify_Login(Login.ccmfa)
					.Empty_Out_Cart()	 
					.Goto_MySubscriptions()
					.Access_AutoPayInfo()
					.Validate_AutoPay()
					.Vaildate_PreAuthMessage(savedCardMessage.get("useSavedCardMessage"))
					.Verify_SavedCard_Updated()
					.Goto_MySubscriptions()
					.Access_AutoPayInfo()
					.Validate_Security_Popup_On_Add_Diff_CC(masterCard3DS2NoFriction,billingAddress)
					.Verify_SavedCard_Updated()
					.Goto_MySubscriptions()
					.Access_AutoPayInfo()
					.Validate_Security_Popup_On_Add_Diff_CC(visaCard3DS2Friction,billingAddress)
					.Validate_FrictionCC_AuthPopup(visaCard3DS2Friction, "submit")
					.Verify_SavedCard_Updated()
					.LogOut_Account();
		}
 
 @Test(description= "R51_JUS Existing Company Account Existing Canada Shipping,Existing US billing_Amex_3DS2_No_FF")
	public void R51_Register_JUS_Brazil_Shipping_US_existing_Shipping() {
		home
	    .GoTo_LogIn()
	    .Register_Existing_Account()
	    .Choose_Existing_Company_Account(existingCompanyAccountInfo, AccountType.JUSCOMPANY)
		.Register_By_Providing_Login_Info_And_Login(existingCompanyAccountInfo)
		.Add_Billing_Address(existingCompanyAccountInfo)
		.Goto_AccountDetails()
		.Add_This_Product_To_Cart(simpleProduct.get("hardgoodProduct"))
		.Add_This_Product_To_Cart(simpleProduct.get("onlinelearningProduct"))
		.Add_This_Product_To_Cart(simpleProduct.get("MediaProduct"))
		.Checkout_With_Cart()
		.Add_New_Shipping_Address(CanadaShipping)
		.Use_Default_Shipping_Method()
		.Use_Credit_Card_Payment(amexCard3DS2NoFriction)
		.Add_New_Billing_Address_CC(billingAddress)
		.Edit_this_Cart()
		.Checkout_With_Cart()
		.Use_Existing_Shipping_Address("Canada")
		.Use_Default_Shipping_Method()
		.Use_Credit_Card_Payment(amexCard3DS2NoFriction)
		.Add_New_Billing_Address_CC(billingAddress)
		.Place_Order()
		.Verify_Order()
		.GoTo_AircraftDetails()
		.Add_New_Aircraft(bundlesTier1GPS175GNX375)
		.LogOut_Account();
	}
	
}